platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
#install! 'cocoapods', :deterministic_uuids => false
workspace 'ZSLogWorker_Demo'

target 'ZSLogWorker_Demo' do

  pod 'SSZipArchive'
  pod 'AFNetworking'

  pod 'ZSLogWorker', :path => '../'
  
  project 'ZSLogWorker_Demo/ZSLogWorker_Demo.xcodeproj'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['ENABLE_BITCODE'] = 'NO'
      end
  end
end






        
